export default {
	COLORS: {
		CONTRAST_COLOR: '#F8B537',

		BACKGROUND_COLOR: '#000000',
		BACKGROUND_BUTTON: '#1E1E1E',
		BACKGROUND_INPUT: '#151515',

		COLOR_BUTTON: '#4F4F4F',
		COLOR_INPUT: '#4F4F4F',
		COLOR_CARD: '#FFFFFF',
		COLOR_SECTION: '#FFFFFF',

		COLOR_BUTTON_SIGNIN: '#4FCB6A',
		COLOR_BUTTON_SIGNUP: '#484848',
	},
};
